Added account manager name and registration date to root-agencies
happy-travel/edo pull request #1220
Opened 2021-11-25 15:48 UTC by Raibo

https://github.com/happy-travel/ueda/issues/142

2021-11-25 18:15 UTC, AlexeyShok requested changes

2021-11-25 18:15 UTC, AlexeyShok commented on Api/AdministratorServices/AdminAgencyManagementService.cs
> +                .SingleOrDefaultAsync();
Why is the role of account manager taken from the database and is it checked that the agent has it? Wasn't it possible to just check the rights with a filter by the permishene at the input to the controller? We have already discussed earlier that we should not bind to roles in the code, only to permissions. Since the names of the roles and the list of permissions included in them can change at any time.

2021-11-26 08:30 UTC, Raibo commented on Api/AdministratorServices/AdminAgencyManagementService.cs
> +                .SingleOrDefaultAsync();
So there are several questions in this comment, as I understand it.

1. Why search for an agent with a specific role, not a permission.
Because the task had a clear description: "Name of the Account manager", not "Name of someone who have the ability to do this or that".
This is for the office, not for us. The office want that, we give that to them, unless there is a really good reason not to.

2. Why not send the definition of the "Account manager" to the input of the controller?
Because this will only shift the responsibility to the front-end, which solves nothing.

3. Why use role name, while role name can change?
A role has only 3 aspects to filter with: Name, permission set and Id. You also mentioned that a permission set might change. Id also might differ between dev and prod. So, we don't have a single aspect to the Role that is solid. 
This means that the problem persists regardless of which aspect of the role we choose to filter it with.

The only way to solve this ambiguity for good I can come up with - is to give roles a new column "Slug" with immutable clear identifier and use it instead.

2021-11-28 20:53 UTC, mingazhev approved these changes

2021-11-29 07:21 UTC, Raibo commented on Api/AdministratorServices/AdminAgencyManagementService.cs
> +                .SingleOrDefaultAsync();
Reworked the changes and now sending empty string there, for now.

2021-11-29 07:24 UTC, AlexeyShok approved these changes

2021-11-29 07:25 UTC, merged