Endpoint to delete unused agencies and it's agents
happy-travel/edo pull request #1250
Opened 2021-12-13 11:56 UTC by Raibo

https://github.com/happy-travel/ueda/issues/147

2021-12-13 12:00 UTC, Raibo commented on Api/AdministratorServices/AgentRemovalService.cs
> +                    .Tap(WriteLogAgentDeleted);
Tap because we already deleted the user from Identity, we cannot cancel this even if logging failed.

2021-12-13 12:00 UTC, Raibo commented on Api/AdministratorServices/AgencyRemovalService.cs
> +                    .Tap(WriteAgencyDeletionToAuditLog));
Tap because we already deleted the user from Identity, we cannot cancel this even if logging failed.

2021-12-13 14:57 UTC, DFSko commented on Api/AdministratorServices/AgentRemovalService.cs
> +                    HttpResponseMessage response = null;
HttpResponseMessage is IDisposable. Could you dispose it at the end?

2021-12-13 14:57 UTC, DFSko commented on Api/Infrastructure/ServiceCollectionExtensions.cs
> +            services.AddClientAccessTokenClient(HttpClientNames.UsersManagementIdentityClient, HttpClientNames.UsersManagementIdentityClient, client =>
You need two clients: one for token management and one for api requests:

services.AddClientAccessTokenClient(tokenManagementClient, apiRequestsClient, client =>

2021-12-13 15:04 UTC, Raibo commented on Api/AdministratorServices/AgencySystemSettingsManagementService.cs
> +                    return Result.Success();
Looks like so. 
Will change to simple `Task`

2021-12-15 00:47 UTC, Raibo commented on Api/AdministratorServices/IAgencyRemovalService.cs
> +        Task<Result> Delete(int agencyId);
Renamed to deletion

2021-12-15 00:57 UTC, Raibo commented on Api/AdministratorServices/AgentRemovalService.cs
> +                    HttpResponseMessage response = null;
Also added to `DirectApiClientManagementService`, since I took the code from there, and response there does not get disposed too.

2021-12-15 07:16 UTC, kirillta requested changes

2021-12-15 07:16 UTC, kirillta commented on Api/AdministratorServices/IAgencyDeletionService.cs
> +    public interface IAgencyDeletionService
The previous name was correct

2021-12-15 10:23 UTC, DFSko approved these changes

2021-12-15 10:25 UTC, Raibo commented on Api/AdministratorServices/IAgencyDeletionService.cs
> +    public interface IAgencyDeletionService
Made it to be `IAgencyRemovalService`, and the method to be `Delete`

2021-12-15 10:37 UTC, kirillta approved these changes

2021-12-16 08:09 UTC, merged