Feature/aa 1324 add endpoint to manage countries in market
happy-travel/edo pull request #1609
Opened 2022-04-06 15:49 UTC by DaniyarAskarov

Issue: https://github.com/happy-travel/agent-app-project/issues/1324
Insomnia: Edo -> Admin -> Locations
Tests: code was tested through unit tests and insomnia
Migrations: has one JsonDocument -> Multilanguage in country entity

Bugs: one bugs when requests to locations/markets/{:marketId}/countries GET. Bugs happens in one case with marketId = 2. And Bug was fixed, problem was with the old cash)

2022-04-06 16:42 UTC, AlexeyShok commented on Api/AdministratorServices/Locations/IMarketManagementService.cs
> +        Task<Result> AddCountries(CountryRequest countryRequest, CancellationToken cancellationToken = default);
ModifyMarketCountries

2022-04-06 16:42 UTC, AlexeyShok commented on Api/AdministratorServices/Locations/IMarketManagementService.cs
> +        Task<Result<List<Country>>> GetCountries(CountryRequest request, CancellationToken cancellationToken = default);
GetMarketCountries

2022-04-06 16:42 UTC, AlexeyShok commented on Api/AdministratorServices/Locations/MarketManagementService.cs
> +                                    .AnyAsync(m => m.Id == marketId && !m.Names.En.Contains(UnknownMarketEnName), cancellationToken);
It is better to compare by unknown market by Id, since we cannot guarantee that the name of any of the countries will contain the word "Unknown"

2022-04-06 16:42 UTC, AlexeyShok commented on Api/AdministratorServices/Locations/MarketManagementService.cs
> +            async Task Add()
Modify

2022-04-06 16:42 UTC, AlexeyShok commented on Api/AdministratorServices/Locations/MarketManagementStorage.cs
> +        public Task<List<Country>> GetCountries(int marketId, CancellationToken cancellationToken)
GetMarketCountries

2022-04-06 16:42 UTC, AlexeyShok commented on Api/AdministratorServices/Locations/MarketManagementStorage.cs
> +        public async Task RefreshCountries(int marketId, CancellationToken cancellationToken)
RefreshMarketCountries

2022-04-06 16:42 UTC, AlexeyShok commented on Api/Controllers/AdministratorControllers/MarketManagementController.cs
> +        ///     Adds countries to market.
Modifies the composition of the market countries

2022-04-06 16:42 UTC, AlexeyShok commented on Api/Controllers/AdministratorControllers/MarketManagementController.cs
> +        public async Task<IActionResult> AddCountries([FromRoute] int marketId, [FromBody] CountryRequest countryRequest)
ModifyMarketCountries

2022-04-06 16:42 UTC, AlexeyShok commented on Api/Controllers/AdministratorControllers/MarketManagementController.cs
> +        public async Task<IActionResult> GetCountries([FromRoute] int marketId)
GetMarketCountries

2022-04-06 16:59 UTC, AlexeyShok requested changes

2022-04-06 16:59 UTC, AlexeyShok commented on Api/AdministratorServices/Locations/MarketManagementService.cs
> +            Result RemoveValidate()
GetValidate or Validate

2022-04-06 16:59 UTC, AlexeyShok commented on Api/Models/Locations/CountryRequest.cs
> +        public int? MarketId { get; }
int MarketId

2022-04-06 16:59 UTC, AlexeyShok commented on Api/Models/Locations/CountryRequest.cs
> +        public List<string>? CountryCodes { get; }
List<string> CountryCodes

2022-04-06 21:05 UTC, kirillta commented on Api/AdministratorServices/Locations/MarketManagementService.cs
> +            async Task SetUnkownToDifferences()
I advise `SetDifferencesToUnkownMarket`, and rename `Unknown` to `Default` or `Global` to avoid misuses

2022-04-07 06:21 UTC, DaniyarAskarov commented on Api/AdministratorServices/Locations/MarketManagementService.cs
> +                        Func<int, CancellationToken, Task<bool>> IsNotUnknown()
Removed from code

2022-04-07 08:58 UTC, kirillta commented on Api/AdministratorServices/Locations/IMarketManagementStorage.cs
> +        Task<List<Country>> GetCountries(int marketId, CancellationToken cancellationToken);
`GetMarketCountries` I believe

2022-04-07 08:58 UTC, kirillta commented on Api/AdministratorServices/Locations/MarketManagementService.cs
> +            Result RemoveValidate()
Not resolved

2022-04-07 08:59 UTC, DaniyarAskarov commented on HappyTravel.Edo.Data/Migrations/20220406152307_ChangeJsonDocumentToMultilanguageInCountry.cs
> +    public partial class ChangeJsonDocumentToMultilanguageInCountry : Migration
Empty migration with JsonDocument type changes in snapshot.

2022-04-07 09:04 UTC, DaniyarAskarov commented on Api/Models/Locations/CountryRequest.cs
> +        public static CountryRequest CreateEmpty(int marketId) => new(marketId, null);
Code was removed

2022-04-07 09:05 UTC, DaniyarAskarov commented on Api/AdministratorServices/Locations/MarketManagementService.cs
> +            async Task SetUnkownToDifferences()
Will be fixed in next pr

2022-04-07 10:18 UTC, AlexeyShok approved these changes

2022-04-07 10:33 UTC, merged