Feature/aa 1921 apply commission by credit card to another currency
happy-travel/edo pull request #2369
Opened 2022-11-02 10:11 UTC by DaniyarAskarov

Issue: https://github.com/happy-travel/agent-app-project/issues/1921

2022-11-03 09:01 UTC, AlexeyShok approved these changes

2022-11-07 05:34 UTC, DFSko commented on Api/Models/Accommodations/Rate.cs
> +        public Rate(Rate rate, MoneyAmount finalPrice, decimal commission, MoneyAmount creditCardPrice)
Comment

2022-11-07 09:50 UTC, suhan3z commented on Api/Services/Accommodations/Availability/RoomContractSetPriceProcessor.cs
> +
Pls do Ctrl+Alt+L before pull request in RSharp or Rider

2022-11-07 09:52 UTC, suhan3z commented on Api/Services/Accommodations/Availability/RoomContractSetPriceProcessor.cs
> +        public static List<RoomContractSet> AlignPrices(List<RoomContractSet> sourceRoomContractSets)
Comments

2022-11-07 09:52 UTC, suhan3z commented on Api/Services/Accommodations/Availability/RoomContractSetPriceProcessor.cs
> +        public static RoomContractSet AlignPrices(RoomContractSet roomContractSet)
Comments

2022-11-07 09:53 UTC, suhan3z commented on Api/Services/Accommodations/Availability/Steps/BookingEvaluation/BookingEvaluationPriceProcessor.cs
> +        public async Task<RoomContractSetAvailability> AlignPrices(RoomContractSetAvailability value)
Comments

2022-11-07 09:54 UTC, suhan3z commented on Api/Services/Accommodations/Availability/Steps/BookingEvaluation/BookingEvaluationPriceProcessor.cs
> +        public async Task<RoomContractSetAvailability> AlignPrices(RoomContractSetAvailability value)
The name doesn't reveal update of availability

2022-11-07 09:54 UTC, suhan3z commented on Api/Services/Accommodations/Availability/Steps/BookingEvaluation/BookingEvaluationPriceProcessor.cs
> +        public async Task<RoomContractSetAvailability> ApplyCommission(RoomContractSetAvailability value, AgentContext agent)
The name doesn't reveal update of availability

2022-11-07 09:54 UTC, suhan3z commented on Api/Services/Accommodations/Availability/Steps/BookingEvaluation/BookingEvaluationPriceProcessor.cs
>          private static async ValueTask<RoomContractSetAvailability> ProcessPrices(RoomContractSetAvailability value,
The same

2022-11-07 09:57 UTC, suhan3z commented on Api/Services/Accommodations/Availability/Steps/RoomSelection/IRoomSelectionPriceProcessor.cs
> +        Task<SingleAccommodationAvailability> AlignPrices(SingleAccommodationAvailability availabilityDetails);
Comment interfaces as well

2022-11-07 09:57 UTC, suhan3z commented on Api/Services/Accommodations/Availability/Steps/RoomSelection/RoomSelectionPriceProcessor.cs
> +        public async Task<SingleAccommodationAvailability> AlignPrices(SingleAccommodationAvailability source)
Comment

2022-11-07 09:57 UTC, suhan3z commented on Api/Services/Accommodations/Availability/Steps/RoomSelection/RoomSelectionPriceProcessor.cs
> +        public async Task<SingleAccommodationAvailability> ApplyCommission(SingleAccommodationAvailability source, AgentContext agent)
Comment

2022-11-07 09:57 UTC, suhan3z commented on Api/Services/Accommodations/Availability/Steps/RoomSelection/RoomSelectionPriceProcessor.cs
> +        public async Task<SingleAccommodationAvailability> ApplyCommission(SingleAccommodationAvailability source, AgentContext agent)
The name doesn't reveal update of availability

2022-11-07 09:57 UTC, suhan3z commented on Api/Services/Accommodations/Availability/Steps/RoomSelection/RoomSelectionPriceProcessor.cs
> +        public async Task<SingleAccommodationAvailability> AlignPrices(SingleAccommodationAvailability source)
The name doesn't reveal update of availability

2022-11-07 09:58 UTC, suhan3z commented on Api/Services/Accommodations/Availability/Steps/WideAvailabilitySearch/IWideAvailabilityPriceProcessor.cs
> +        Task<List<AccommodationAvailabilityResult>> AlignPrices(List<AccommodationAvailabilityResult> results);
Comments

2022-11-07 09:59 UTC, suhan3z commented on Api/Services/Accommodations/Availability/Steps/WideAvailabilitySearch/WideAvailabilityPriceProcessor.cs
> +        public async Task<List<AccommodationAvailabilityResult>> AlignPrices(List<AccommodationAvailabilityResult> results)
The name doesn't reveal update of availability. And why there's so many nearly the same AlignPrices and ApplyComissions?

2022-11-07 10:00 UTC, suhan3z commented on Api/Services/Accommodations/Availability/Steps/WideAvailabilitySearch/WideAvailabilitySearchService.cs
> +            bool ApplyingAdditionalCommissionNeeded()
thats the 3rd mention of the ApplyingAdditionalCommissionNeeded maybe it should go to the utility method?

2022-11-07 10:01 UTC, suhan3z requested changes
According to comments

2022-11-07 11:37 UTC, suhan3z approved these changes

2022-11-07 11:40 UTC, merged