Feature/nijo 1023 added agency and counterparty activation
happy-travel/edo pull request #281
Opened 2020-11-06 11:35 UTC by hasmikharutyunyan

2020-11-06 12:32 UTC, kirillta requested changes

2020-11-06 12:32 UTC, kirillta commented on Api/Controllers/AdministratorControllers/CounterpartiesController.cs
> +        [HttpPut("agencies/{agencyId}/change-activity-status")]
Don't put an action and its subject in one route section. Should be like `activity-status/change`. But also I don't like word _activity_ here

2020-11-06 12:32 UTC, kirillta commented on Api/AdministratorServices/CounterpartyManagementService.cs
> +                .Tap(() => WriteCounterpartyActivityStatusChangeToAuditLog(counterpartyId, reason));
Shouldn't that line be within transaction?

2020-11-06 12:36 UTC, hasmikharutyunyan commented on Api/AdministratorServices/CounterpartyManagementService.cs
> +                .Tap(() => WriteCounterpartyActivityStatusChangeToAuditLog(counterpartyId, reason));
I think write log can be independent operation

2020-11-06 12:37 UTC, hasmikharutyunyan commented on Api/Controllers/AdministratorControllers/CounterpartiesController.cs
> +        [HttpPut("agencies/{agencyId}/change-activity-status")]
I thoght about oter word to describe this two states and found `ActivityStatus` do you have another suggestion?

2020-11-06 14:11 UTC, mingazhev commented on Api/Controllers/AdministratorControllers/CounterpartiesController.cs
> +        [HttpPut("agencies/{agencyId}/change-activity-status")]
deactivate and activate as different verbs was ok for me

2020-11-06 14:12 UTC, mingazhev commented on Api/AdministratorServices/CounterpartyManagementService.cs
> +                .Tap(() => WriteCounterpartyActivityStatusChangeToAuditLog(counterpartyId, reason));
If it is an audit log, it should come in same transaction. Both should succeed or none

2020-11-06 14:14 UTC, hasmikharutyunyan commented on Api/Controllers/AdministratorControllers/CounterpartiesController.cs
> +        [HttpPut("agencies/{agencyId}/change-activity-status")]
So, you think is better to have two api s for that?

2020-11-06 14:14 UTC, mingazhev commented on Api/Models/Management/Enums/ActivityStatus.cs
> +    public enum ActivityStatus
Do we need an enum for two statuses?

2020-11-06 14:14 UTC, mingazhev commented on Api/Controllers/AdministratorControllers/CounterpartiesController.cs
> +        [HttpPut("agencies/{agencyId}/change-activity-status")]
Yes, I think it will be better

2020-11-06 14:17 UTC, hasmikharutyunyan commented on Api/Models/Management/Enums/ActivityStatus.cs
> +    public enum ActivityStatus
It is for api to indicate status

2020-11-06 14:19 UTC, hasmikharutyunyan commented on Api/Controllers/AdministratorControllers/CounterpartiesController.cs
> +        [HttpPut("agencies/{agencyId}/change-activity-status")]
I thought and about that and prefer to have one api, to not repeat the logic

2020-11-06 14:40 UTC, kirillta commented on Api/Controllers/AdministratorControllers/CounterpartiesController.cs
> +        [HttpPut("agencies/{agencyId}/change-activity-status")]
The logic remains the same, just two endpoints leading to one private method, though

2020-11-09 10:52 UTC, kirillta approved these changes

2020-11-09 11:47 UTC, kirillta approved these changes

2020-11-09 13:56 UTC, mingazhev commented on Api/Controllers/AdministratorControllers/CounterpartiesController.cs
> +        [HttpPut("{counterpartyId}/activate")]
I think it'll better to use POST for such requests.
We already have a verb "activate" and it's better to use POST for actions that do not fit REST verbs

2020-11-09 13:56 UTC, mingazhev commented on Api/Models/Management/ActivityStatusChangeRequest.cs
> +
Redundant blank line

2020-11-09 13:56 UTC, mingazhev commented on Api/Models/Management/ActivityStatusChangeRequest.cs
> +        public ActivityStatusChangeRequest(string reason)
Shouldn't  [jsonconstructor] be present there?

2020-11-09 13:56 UTC, mingazhev commented on Api/Models/Management/AuditEvents/CounterpartActivityStatusChangeEventData.cs
> +    public readonly struct CounterpartActivityStatusChangeEventData
Conterpart**y**

2020-11-09 13:56 UTC, mingazhev commented on HappyTravel.Edo.Common/Enums/ManagementEventType.cs
> +
Redundant blank line

2020-11-09 13:56 UTC, mingazhev commented on HappyTravel.Edo.UnitTests/Tests/AdministratorServices/CounterpartyManagementServiceTests/ActivationTests.cs
> +        private readonly AdministratorServicesMockCreationHelper _mockCreationHelper;
Why do we need a shareable field there? Looks like moving its creation to method will be better

2020-11-09 14:11 UTC, hasmikharutyunyan commented on Api/Controllers/AdministratorControllers/CounterpartiesController.cs
> +        [HttpPut("{counterpartyId}/activate")]
I think POST is better for creation

2020-11-09 14:13 UTC, hasmikharutyunyan commented on HappyTravel.Edo.UnitTests/Tests/AdministratorServices/CounterpartyManagementServiceTests/ActivationTests.cs
> +        private readonly AdministratorServicesMockCreationHelper _mockCreationHelper;
You mean,  have data here not in separate file ?

2020-11-10 00:57 UTC, Raibo approved these changes

2020-11-10 10:43 UTC, hasmikharutyunyan commented on Api/Models/Management/ActivityStatusChangeRequest.cs
> +        public ActivityStatusChangeRequest(string reason)
It is work without that attribute

2020-11-10 11:05 UTC, mingazhev commented on Api/Controllers/AdministratorControllers/CounterpartiesController.cs
> +        [HttpPut("{counterpartyId}/activate")]
Yes, PUT is good for idemponent, but this request is not idemponent. End in general - PUT is to update something, that's how it is in wiki:
`Store the representation in the request body as the (new) state of the resource. Subsequent GET access on the resource is expected to return this representation with HTTP status 200 until PATCHed, a different representation is PUT, or the state of the resource is DELETEd. `

Do we have new state in the request body?

2020-11-10 11:05 UTC, mingazhev commented on HappyTravel.Edo.UnitTests/Tests/AdministratorServices/CounterpartyManagementServiceTests/ActivationTests.cs
> +        private readonly AdministratorServicesMockCreationHelper _mockCreationHelper;
I mean two things:
1. These two lines are repeated in each test and do not describe anything useful:
```
var context = _mockCreationHelper.GetContextMock().Object;
            var counterpartyManagementService = _mockCreationHelper.GetCounterpartyManagementService(context);
```

this could be moved to a method at least

2. Looks like there is no state that is needed to be shared. Creating and instantiating it in counstructor is worse than getting in method.

2020-11-10 11:12 UTC, mingazhev commented on Api/Controllers/AdministratorControllers/CounterpartiesController.cs
> +        [HttpPut("{counterpartyId}/activate")]
On the other hand, POST is used like "generic" or "multipurpose" request

2020-11-10 11:41 UTC, hasmikharutyunyan commented on HappyTravel.Edo.UnitTests/Tests/AdministratorServices/CounterpartyManagementServiceTests/ActivationTests.cs
> +        private readonly AdministratorServicesMockCreationHelper _mockCreationHelper;
1. In tests for checking result is used context, for example an.
I have done those for consistency with other tests, anyway i think it is not a big deal.

2020-11-11 13:08 UTC, mingazhev approved these changes
Do not merge for now, will deploy later

2020-11-12 14:27 UTC, merged