added checks bookings status in invoice sending
happy-travel/edo pull request #282
Opened 2020-11-09 09:01 UTC by DFSko

2020-11-09 11:54 UTC, mingazhev requested changes

2020-11-09 11:54 UTC, mingazhev commented on Api/Services/Accommodations/Bookings/BookingDocumentsService.cs
> +            var notAllowedStatuses = new List<BookingStatuses> {BookingStatuses.Cancelled, BookingStatuses.Rejected};
1. Please use hashset for such things
2. Use a static property if it is not supposed to be changed

2020-11-09 11:54 UTC, mingazhev commented on Api/Services/Accommodations/Bookings/BookingDocumentsService.cs
> +            if (notAllowedStatuses.Contains(booking.Status))
Need more descriptive message there. For example, "Invoice sending is not allowed for status '{status}'"

2020-11-09 11:57 UTC, kirillta requested changes

2020-11-09 11:57 UTC, kirillta commented on Api/Services/Accommodations/Bookings/BookingDocumentsService.cs
> +            var notAllowedStatuses = new List<BookingStatuses> {BookingStatuses.Cancelled, BookingStatuses.Rejected};
Those statuses could be moved to a static variable of `HashSet<BookingStatuses>` for better readability

2020-11-09 11:57 UTC, kirillta commented on Api/Services/Accommodations/Bookings/BookingDocumentsService.cs
> +                return Result.Failure<(DocumentRegistrationInfo Metadata, BookingInvoiceData Data)>("Not allowed status");
The error message must clarify an issue but not hide it, like, which status not allowed? Not allowed for what?

2020-11-09 12:00 UTC, kirillta commented
@mingazhev great minds think alike 🤝

2020-11-09 12:30 UTC, kirillta commented on Api/Services/Accommodations/Bookings/BookingDocumentsService.cs
> +        private static readonly HashSet<BookingStatuses> NotAvailableForInvoiceSendingStatuses = new HashSet<BookingStatuses>
Not an issue, but usually we place constructor parameters at the very end, so this hash set should places above them

2020-11-09 12:30 UTC, kirillta commented on Api/Services/Accommodations/Bookings/BookingDocumentsService.cs
> +                return Result.Failure<(DocumentRegistrationInfo Metadata, BookingInvoiceData Data)>($"Invoice sending is not allowed for status '{booking.Status}'");
Please add the enum formatting [library](https://github.com/happy-travel/kanazawa/blob/master/HappyTravel.Formatters/EnumFormatters.cs) here

2020-11-09 12:49 UTC, kirillta approved these changes

2020-11-09 13:57 UTC, mingazhev approved these changes

2020-11-10 08:57 UTC, kirillta requested changes
Since the PR is still here, add tests to it please

2020-11-10 12:26 UTC, mingazhev reviewed
Waiting for the tests

2020-11-10 13:13 UTC, mingazhev requested changes

2020-11-10 13:13 UTC, mingazhev commented on HappyTravel.Edo.UnitTests/Tests/Services/Accommodations/Bookings/BookingDocumentsServiceTests/Invoice/GenerateInvoice.cs
> +    public class GenerateInvoice
Class name should not be represented as a verb

2020-11-10 13:13 UTC, mingazhev commented on HappyTravel.Edo.UnitTests/Tests/Services/Accommodations/Bookings/BookingDocumentsServiceTests/Invoice/GenerateInvoice.cs
> +namespace HappyTravel.Edo.UnitTests.Tests.Services.Accommodations.Bookings.BookingDocumentsServiceTests.Invoice
Looks like this namespace segment should be omitted

2020-11-10 13:13 UTC, mingazhev commented on HappyTravel.Edo.UnitTests/Tests/Services/Accommodations/Bookings/BookingDocumentsServiceTests/Invoice/GenerateInvoice.cs
> +                BookingDocumentsService.NotAvailableForInvoiceStatuses.Contains(b.Status));
Looks like not a good practice:
1. Making property public only for tests
2. Having too much logic in getting.

The best way is to set bookings manually and to know which ids should fail with error.
This could be done with using [Theory] with different values in it.

Good tests should be maximum "black box", these tests are not.

2020-11-10 13:13 UTC, mingazhev commented on HappyTravel.Edo.UnitTests/Tests/Services/Accommodations/Bookings/BookingDocumentsServiceTests/Invoice/GenerateInvoice.cs
> +            var results = await Task.WhenAll(tasks);
This is not descriptive and do not provide any useful information. It's better to run a one task for a single test and await it

2020-11-10 13:13 UTC, mingazhev commented on HappyTravel.Edo.UnitTests/Tests/Services/Accommodations/Bookings/BookingDocumentsServiceTests/Invoice/GenerateInvoice.cs
> +        private static List<Booking> GenerateBookings()
Same there. You should not try to create test data automatically, it should be manually created in a special property or method.
Like
List<Booking> Bookings = new {
new Booking { ... },
new Booking { ... },
}

2020-11-10 13:13 UTC, mingazhev commented on HappyTravel.Edo.UnitTests/Tests/Services/Accommodations/Bookings/BookingDocumentsServiceTests/Invoice/GenerateInvoice.cs
> +        private static List<Booking> GenerateBookings()
You should look to the tests from following point:
"Some person can see all bookings easily and then execute a method and get expected result. e.g. I see that booking with id=123 is not confirmed" (from first glance) and I know that generating invoice for it should fail.

In your implementation logic is too hard to understand from the first glance

2020-11-10 13:13 UTC, mingazhev commented on HappyTravel.Edo.UnitTests/Tests/Services/Accommodations/Bookings/BookingDocumentsServiceTests/Invoice/GenerateInvoice.cs
> +        public async Task generate_invoice_from_not_allowed_booking_status_should_error()
Please look for method naming in other tests:
1. They start from capital letter
2. They could be read as a sentence in english

2020-11-10 15:34 UTC, kirillta approved these changes
No objections except those what are made by @mingazhev

2020-11-12 10:28 UTC, mingazhev approved these changes
Good

2020-11-12 10:31 UTC, merged