Feature/nijo 1017 disable enable agency relation
happy-travel/edo pull request #283
Opened 2020-11-10 00:59 UTC by Raibo

2020-11-10 09:48 UTC, mingazhev requested changes
(there were not actual comment, I've removed)

2020-11-10 09:48 UTC, mingazhev commented on Api/Services/Agents/AgentAgencyEnablementService.cs
> +                .Ensure(() => agentContext.IsUsingAgency(agencyId), "You can only disable agents in an agency you are currently using")
We've discussed and decided to not use such methods, where agency id is passed from endpoint.
We always have an agent context bound to request, where current working agency id is present.
So you should just get agency id from there and then check that disabling agent id is present there

2020-11-10 09:48 UTC, mingazhev commented on Api/Services/Agents/AgentAgencyEnablementService.cs
> +                .Ensure(() => agentContext.IsUsingAgency(agencyId), "You can only disable agents in an agency you are currently using")
Or maybe just respond that this agent is not found, if it is not found in an agency in which current agent is working in this request

2020-11-10 09:48 UTC, mingazhev commented on HappyTravel.Edo.Data/Migrations/20201110004609_AddIsEnabledToRelation.cs
> +        protected override void Up(MigrationBuilder migrationBuilder)
Since you've changed "Permission" need to migrate current agents with "All" permissions to add a new permission

2020-11-10 09:48 UTC, mingazhev commented on HappyTravel.Edo.UnitTests/Tests/Services/Agents/AgentAgencyEnablementServiceTests/AgentAgencyEnablementServiceTests.cs
> +            SetRelations();
Why this is needed both in methods and there?

2020-11-10 09:48 UTC, mingazhev commented on HappyTravel.Edo.UnitTests/Tests/Services/Agents/AgentAgencyEnablementServiceTests/AgentAgencyEnablementServiceTests.cs
> +            _agentAgencyEnablementService = new AgentAgencyEnablementService(edoContextMock.Object);
Could you remove instantiating of this service to method and get rid of the shared state?

2020-11-10 09:48 UTC, mingazhev commented on Api/Controllers/AgentControllers/AgentAgencyEnablementController.cs
> +    public class AgentAgencyEnablementController : BaseController
Why not in `AgentsController`?

2020-11-10 09:48 UTC, mingazhev commented on HappyTravel.Edo.Common/Enums/InAgencyPermissions.cs
> +            AgentEnablement // 8190
This wording looks a bit weird for me.
Maybe something like `AgentStatusManagement`?

2020-11-10 10:10 UTC, mingazhev commented
> 
> 
> Could not find any checks that agent is not disabled. If I'm not wrong we've decided to permit disabled agents using system



> 
> 
> Could not find any checks that agent is not disabled. If I'm not wrong we've decided to permit disabled agents using system

Sorry, this is in another task

2020-11-10 11:02 UTC, kirillta commented on HappyTravel.Edo.Common/Enums/InAgencyPermissions.cs
> +            AgentEnablement // 8190
Agree

2020-11-10 11:46 UTC, hasmikharutyunyan commented on Api/Controllers/AgentControllers/AgentAgencyEnablementController.cs
> +    public class AgentAgencyEnablementController : BaseController
Maybe here also we can use Active name for consistency ?

2020-11-10 11:47 UTC, hasmikharutyunyan commented on Api/Controllers/AgentControllers/AgentAgencyEnablementController.cs
> +        public async Task<IActionResult> Enable(int agencyId, int agentId)
In other apis we  are using reason

2020-11-10 11:52 UTC, hasmikharutyunyan commented on Api/Controllers/AgentControllers/AgentAgencyEnablementController.cs
> +        public async Task<IActionResult> Disable(int agencyId, int agentId)
Those apis not for admin, maybe we need apis for administrator?

2020-11-10 12:39 UTC, Raibo commented on Api/Controllers/AgentControllers/AgentAgencyEnablementController.cs
> +        public async Task<IActionResult> Enable(int agencyId, int agentId)
The only place reason is used elsewhere, as I can see, is AuditLog.
I personally think that here we don't need to use AuditLog here.

2020-11-10 12:41 UTC, Raibo commented on Api/Controllers/AgentControllers/AgentAgencyEnablementController.cs
> +        public async Task<IActionResult> Disable(int agencyId, int agentId)
Well, there is nothing said about it in the task, and I also think there is no need for this, but lets see what others will say.
@kirillta @mingazhev

2020-11-10 12:43 UTC, mingazhev commented on Api/Controllers/AgentControllers/AgentAgencyEnablementController.cs
> +        public async Task<IActionResult> Disable(int agencyId, int agentId)
I don't think that we need it for admins, at least now. This is agent API

2020-11-10 12:45 UTC, Raibo commented on HappyTravel.Edo.UnitTests/Tests/Services/Agents/AgentAgencyEnablementServiceTests/AgentAgencyEnablementServiceTests.cs
> +            SetRelations();
Fixed

2020-11-10 12:45 UTC, Raibo commented on HappyTravel.Edo.UnitTests/Tests/Services/Agents/AgentAgencyEnablementServiceTests/AgentAgencyEnablementServiceTests.cs
> +            _agentAgencyEnablementService = new AgentAgencyEnablementService(edoContextMock.Object);
Why not

2020-11-10 12:46 UTC, Raibo commented on Api/Controllers/AgentControllers/AgentAgencyEnablementController.cs
> +    public class AgentAgencyEnablementController : BaseController
Moved to `AgentsController`

2020-11-10 12:46 UTC, Raibo commented on HappyTravel.Edo.Common/Enums/InAgencyPermissions.cs
> +            AgentEnablement // 8190
Renamed

2020-11-10 13:09 UTC, Raibo commented
Note the change `AgentsController : ControllerBase` -> `AgentsController : BaseController`.
Should be okay though.

2020-11-10 13:09 UTC, Raibo commented on Api/Controllers/AgentControllers/AgentAgencyEnablementController.cs
> +    public class AgentAgencyEnablementController : BaseController
Changed

2020-11-10 13:25 UTC, Raibo commented on HappyTravel.Edo.Data/Migrations/20201110004609_AddIsEnabledToRelation.cs
> +        protected override void Up(MigrationBuilder migrationBuilder)
Done

2020-11-10 15:02 UTC, mingazhev commented on Api/Controllers/AgentControllers/AgentsController.cs
> +        [HttpPut("agents/{agentId}/enable")]
let's discuss a verb tomorrow, I think put is not suitable, it should be POST

2020-11-10 15:28 UTC, kirillta requested changes

2020-11-10 15:28 UTC, kirillta commented on Api/Controllers/AgentControllers/AgentsController.cs
> +        [HttpPut("agents/{agentId}/enable")]
Yes POST is more suitable

2020-11-10 15:28 UTC, kirillta commented on Api/Services/Agents/AgentStatusManagementService.cs
> +        public async Task<Result> Enable(int agentIdToEnable, AgentContext agentContext)
I wonder if we could move `AgentContextService` dependency to class level?

2020-11-10 15:28 UTC, kirillta commented on Api/Services/Agents/AgentStatusManagementService.cs
> +                .Ensure(r => !r.IsActive, "Agent is already enabled")
`PUT` is idempotent, you mustn't return an error at this case

2020-11-11 02:59 UTC, Raibo commented on Api/Services/Agents/AgentStatusManagementService.cs
> +        public async Task<Result> Enable(int agentIdToEnable, AgentContext agentContext)
But why?

2020-11-11 13:15 UTC, hasmikharutyunyan commented on Api/Services/Agents/IAgentStatusManagementService.cs
> +        Task<Result> Enable(int agentIdToEnable, AgentContext agentContext);
I think just agentId more readable

2020-11-12 14:18 UTC, Raibo commented on Api/Services/Agents/IAgentStatusManagementService.cs
> +        Task<Result> Enable(int agentIdToEnable, AgentContext agentContext);
There is also agent id of the agent who did the request

2020-11-12 14:30 UTC, mingazhev approved these changes

2020-11-13 07:06 UTC, merged