add room supplier reference code to voucher
happy-travel/edo pull request #284
Opened 2020-11-10 04:00 UTC by DFSko

2020-11-10 08:58 UTC, mingazhev approved these changes

2020-11-10 11:01 UTC, kirillta requested changes
It would be nice if you add tests to this class as well

2020-11-11 17:15 UTC, DFSko commented
> It would be nice if you add tests to this class as well

testing invoices and vouchers added in NIJO-1027 branch

2020-11-11 21:35 UTC, kirillta approved these changes

2020-11-12 05:00 UTC, merged