Feature/NIJO-1028 added additional properties to booking documents
happy-travel/edo pull request #286
Opened 2020-11-11 20:11 UTC by DFSko

2020-11-12 10:27 UTC, mingazhev requested changes

2020-11-12 10:27 UTC, mingazhev commented on Api/Extensions/MaskStringExtension.cs
> +    public static class MaskStringExtension
You should use Formatters.PersonNameFormatters instead of this

2020-11-12 10:27 UTC, mingazhev commented on Api/Models/Payments/PaymentReceipt.cs
> +
Just one blank line will be enough

2020-11-12 10:27 UTC, mingazhev commented on Api/Services/Accommodations/Bookings/BookingDocumentsService.cs
> +        private static readonly HashSet<BookingStatuses> InvoiceCanceledBookingStatuses = new HashSet<BookingStatuses>
I think we should review documentation for consistency. We do not allow sending invoices for cancelled bookings.
Should we use invoice statuses - actual or cancelled?
I think we do not

2020-11-12 11:01 UTC, DFSko commented on Api/Extensions/MaskStringExtension.cs
> +    public static class MaskStringExtension
Formatters.PersonNameFormatters takes two strings (firstname and lastname separately), but MainPassengerName is one string

2020-11-12 11:17 UTC, DFSko commented on Api/Models/Payments/PaymentReceipt.cs
> +
Many other structures have two blank lines after constructor, including this class. Need to fix a whole class?

2020-11-12 11:20 UTC, DFSko commented on Api/Services/Accommodations/Bookings/BookingDocumentsService.cs
> +        private static readonly HashSet<BookingStatuses> InvoiceCanceledBookingStatuses = new HashSet<BookingStatuses>
Status calculated on generating invoice and stored in Invoices table in json data. This hashset needed for calculating invoice status

2020-11-12 11:25 UTC, DFSko commented on Api/Models/Payments/PaymentReceipt.cs
> +
This line removed

2020-11-13 10:54 UTC, mingazhev commented on Api/Extensions/MaskStringExtension.cs
> +    public static class MaskStringExtension
It's better to add full main passenger name to the invoice (or maybe add already masked) and make sure that passenger name masking works identically in all cases

2020-11-13 10:55 UTC, mingazhev commented on Api/Services/Accommodations/Bookings/BookingDocumentsService.cs
> +        private static readonly HashSet<BookingStatuses> InvoiceCanceledBookingStatuses = new HashSet<BookingStatuses>
I mean that we do not need to add such thing as invoice status, at least for now. I'll correct the documentation.

2020-11-16 09:06 UTC, DFSko commented on Api/Extensions/MaskStringExtension.cs
> +    public static class MaskStringExtension
fixed

2020-11-16 11:05 UTC, mingazhev approved these changes

2020-11-16 11:17 UTC, merged