Feature/nijo 1019 uploading images
happy-travel/edo pull request #294
Opened 2020-11-17 18:48 UTC by Raibo

2020-11-18 05:54 UTC, mingazhev commented on Api/Services/Files/ImageFileService.cs
> +            var agentContext = await _agentContextService.GetAgent();
You should pass agentContext from controller

2020-11-18 05:54 UTC, mingazhev commented on Api/Services/Files/ImageFileService.cs
> +        private readonly List<string> _imageExtensions = new List<string>{"jpeg", "jpg"};
Please use hashset for such things

2020-11-18 05:54 UTC, mingazhev commented on Api/Services/Files/ImageFileService.cs
> +        private readonly List<string> _imageExtensions = new List<string>{"jpeg", "jpg"};
And this could be static readonly

2020-11-18 05:54 UTC, mingazhev commented on Api/Services/Files/ImageFileService.cs
> +                    .Ensure(() => _imageExtensions.Contains(Path.GetExtension(file?.FileName)?.ToLower()), "The file must have extension of a jpeg image")
ToLowerInvariant

2020-11-18 05:54 UTC, mingazhev commented on Api/Controllers/AgentControllers/AgencyImagesController.cs
> +        public async Task<IActionResult> Add([FromForm] IFormFile file) => OkOrBadRequest(await _imageFileService.Add(file));
Don't think that we need such general-purpose endpoint.
For now we need a banner and logo only.
Why not loading and getting them throw separate endpoints?

@kirillta what do you think?

2020-11-18 20:26 UTC, AlexeyShok commented on Api/Controllers/AgentControllers/AgencyImagesController.cs
> +        public async Task<IActionResult> Add([FromForm] IFormFile file) => OkOrBadRequest(await _imageFileService.Add(file));
Why is the HttpPut request used? If the method "Add" adds a picture then it's should be a HttpPost. Either the method is named incorrectly.

2020-11-18 20:49 UTC, AlexeyShok commented on Api/Services/Files/ImageFileService.cs
> +                await using var stream = file.OpenReadStream();
Problems may arise due to incorrect work with the file stream. The stream is opened for reading twice: during validation and then when loaded into S3. Possible slowdown or crash when rereading from the file stream. This solution needs to be tested thoroughly.

2020-11-18 22:10 UTC, kirillta commented on Api/Services/Files/ImageFileService.cs
> +            var agentContext = await _agentContextService.GetAgent();
Why, isn't that an unnecessary dependency?

2020-11-18 22:20 UTC, kirillta requested changes

2020-11-18 22:20 UTC, kirillta commented on Api/Controllers/AgentControllers/AgencyImagesController.cs
> +        [ProducesResponseType(typeof(ProblemDetails), (int) HttpStatusCode.BadRequest)]
This method returns only 200

2020-11-18 22:20 UTC, kirillta commented on Api/Models/Agencies/SlimUploadedImage.cs
> +        public string Link { get; }
If I remember right we name it `Url` in other places @AlexeyShok

2020-11-19 16:09 UTC, AlexeyShok commented on Api/Models/Agencies/SlimUploadedImage.cs
> +        public string Link { get; }
Yes, we named it Url in hiroshima.

2020-11-21 10:35 UTC, Raibo commented on Api/Controllers/AgentControllers/AgencyImagesController.cs
> +        public async Task<IActionResult> Add([FromForm] IFormFile file) => OkOrBadRequest(await _imageFileService.Add(file));
@AlexeyShok , HttpPut is used due to the fact that new picture with the same name replaces the old one.
If you think that method named incorrectly, suggest a better name.

2020-11-21 12:21 UTC, Raibo commented on Api/Services/Files/ImageFileService.cs
> +            var agentContext = await _agentContextService.GetAgent();
In previous review I was told to move agentContext from controller to service. 
Here I am told to move it from service to controller.
This is strange.

2020-11-21 12:38 UTC, Raibo commented on Api/Services/Files/ImageFileService.cs
> +                await using var stream = file.OpenReadStream();
Changed to save bytes and memory stream

2020-11-21 12:38 UTC, Raibo commented on Api/Models/Agencies/SlimUploadedImage.cs
> +        public string Link { get; }
Renamed

2020-11-21 12:41 UTC, Raibo commented on Api/Controllers/AgentControllers/AgencyImagesController.cs
> +        public async Task<IActionResult> Add([FromForm] IFormFile file) => OkOrBadRequest(await _imageFileService.Add(file));
@mingazhev Why not. So, `.../banner` and `.../logo` PUT/GET endpoints?

2020-11-21 13:00 UTC, mingazhev commented on Api/Services/Files/ImageFileService.cs
> +            var agentContext = await _agentContextService.GetAgent();
I told so? Maybe I was mistaken

2020-11-21 13:01 UTC, mingazhev commented on Api/Controllers/AgentControllers/AgencyImagesController.cs
> +        public async Task<IActionResult> Add([FromForm] IFormFile file) => OkOrBadRequest(await _imageFileService.Add(file));
Yes, separate endpoints will be better. Del will be good too

2020-11-21 13:01 UTC, mingazhev commented on Api/Services/Files/ImageFileService.cs
> +            var agentContext = await _agentContextService.GetAgent();
Could you give a link?

2020-11-21 13:11 UTC, mingazhev commented on Api/Services/Files/ImageFileService.cs
> +            var agentContext = await _agentContextService.GetAgent();
And Kirill is right, could not find where this dependency used now

2020-11-21 13:35 UTC, mingazhev reviewed
Need to change the endpoints logic

2020-11-23 08:12 UTC, Raibo commented on Api/Services/Files/ImageFileService.cs
> +            var agentContext = await _agentContextService.GetAgent();
Here is the link
https://github.com/happy-travel/edo/pull/283#discussion_r520647510

2020-11-23 10:55 UTC, AlexeyShok commented on Api/Controllers/AgentControllers/AgencyImagesController.cs
> +        public async Task<IActionResult> Add([FromForm] IFormFile file) => OkOrBadRequest(await _imageFileService.Add(file));
If HttpPut remains, then I would call method AddOrReplace or Replace, but not Add

2020-11-23 12:35 UTC, mingazhev commented on Api/Controllers/AgentControllers/AgencyImagesController.cs
> +        public async Task<IActionResult> AddOrReplaceBanner([FromForm] IFormFile file)
SetBanner maybe?

2020-11-23 12:35 UTC, mingazhev approved these changes
With a small comment

2020-11-23 15:13 UTC, kirillta approved these changes

2020-11-23 15:23 UTC, Raibo commented on Api/Controllers/AgentControllers/AgencyImagesController.cs
> +        public async Task<IActionResult> Add([FromForm] IFormFile file) => OkOrBadRequest(await _imageFileService.Add(file));
I also considered AddOrReplace, but after discussing with Vadim, renamed to Set

2020-11-23 15:23 UTC, merged