credit card payment confirmation implementation
happy-travel/edo pull request #296
Opened 2020-11-19 04:18 UTC by DFSko

2020-11-19 12:24 UTC, kirillta requested changes

2020-11-19 12:24 UTC, kirillta commented on Api/Services/Accommodations/Bookings/BookingRegistrationService.cs
> +            string languageCode, bool withBookingOnSupplier = true)
Boolean variables must start from a verb by our guidelines, like `isBookedOnSupplier`

2020-11-19 12:24 UTC, kirillta commented on Api/Services/Accommodations/Bookings/BookingCreditCardPaymentConfirmationService.cs
> +                .Tap(ProcessResponse)
Do you really need `Tap` here?

2020-11-19 18:11 UTC, mingazhev requested changes
There are some comments and I'll recheck the main logic tomorrow

2020-11-19 18:11 UTC, mingazhev commented on Api/Controllers/AdministratorControllers/PaymentsController.cs
> +        [HttpGet("confirm/{bookingId}")]
We can discuss that if this comment is not clear enough

2020-11-19 18:11 UTC, mingazhev commented on Api/Controllers/AdministratorControllers/PaymentsController.cs
> +        public async Task<IActionResult> GetBookingsWithUnconfirmedCreditCardPayments(int bookingId)
Method name looks a bit confusing. It says that we get "booking**s**" but uses one booking id as parameter

2020-11-19 18:11 UTC, mingazhev commented on Api/Services/Agents/HttpBasedAgentContextService.cs
> +        public async ValueTask<AgentContext> GetAgent(int agentId)
Agent context is used for getting current agent only, based on http request.
You should get agent from another place, and better to get it not as an AgentContext (need another model)

2020-11-19 18:11 UTC, mingazhev commented on Api/Services/Agents/HttpBasedAgentContextService.cs
> +            return await (from agent in _context.Agents
Same there. We had such lines as a crutch to support some features and they were removed during technical dept refactoring.
This is not a proper place to get or set agent by it's Id

2020-11-20 03:08 UTC, DFSko commented on Api/Services/Accommodations/Bookings/BookingRegistrationService.cs
> +            async Task<Result<Booking, ProblemDetails>> CreditCardPaymentNotify(Booking bookingFromPipe)
Fixed

2020-11-20 03:08 UTC, DFSko commented on Api/Services/Accommodations/Bookings/BookingRegistrationService.cs
> +            string languageCode, bool withBookingOnSupplier = true)
Fixed

2020-11-20 03:17 UTC, DFSko commented on Api/Controllers/AdministratorControllers/PaymentsController.cs
> +        public async Task<IActionResult> GetBookingsWithUnconfirmedCreditCardPayments(int bookingId)
Fixed

2020-11-20 03:17 UTC, DFSko commented on Api/Controllers/AdministratorControllers/PaymentsController.cs
> +        [HttpGet("confirm/{bookingId}")]
Fixed

2020-11-20 03:23 UTC, DFSko commented on Api/Services/Agents/HttpBasedAgentContextService.cs
> +        public async ValueTask<AgentContext> GetAgent(int agentId)
Method VoidMoneyAndCancelBooking requires exactly AgentContext

2020-11-20 11:26 UTC, DFSko commented on Api/Services/Agents/HttpBasedAgentContextService.cs
> +            return await (from agent in _context.Agents
Fixed

2020-11-20 11:26 UTC, DFSko commented on Api/Services/Agents/HttpBasedAgentContextService.cs
> +        public async ValueTask<AgentContext> GetAgent(int agentId)
Fixed

2020-11-20 12:13 UTC, kirillta approved these changes

2020-11-20 18:22 UTC, mingazhev requested changes

2020-11-20 18:22 UTC, mingazhev commented on Api/Services/Accommodations/Bookings/BookingCreditCardPaymentConfirmationService.cs
> +                    : Result.Failure<Booking>($"Could not complete booking. Invalid payment status: {booking.PaymentMethod}");
Status or method?

2020-11-20 18:22 UTC, mingazhev commented on Api/Services/Accommodations/Bookings/BookingCreditCardPaymentConfirmationService.cs
> +            async Task<Result<Booking>> GetBooking()
Looks like this could be replaces by:

`Task<Result<Booking>> GetBooking() => _bookingRecordsManager.Get(bookingId);`

And, tip of the day, your `Result.Success(someObject)` can be implicitly converted from `object`.
So you could return just `bookingRecord` instead of `Result.Success(bookingRecord)`

2020-11-20 18:22 UTC, mingazhev commented on Api/Services/Accommodations/Bookings/BookingCreditCardPaymentConfirmationService.cs
> +            return await _bookingRegistrationService.BookOnProvider(booking, booking.ReferenceCode, booking.LanguageCode)
Looks like incorrect understanding of the task. Booking on provider should be still done after credit card payment, there should be no changes.
In most of the cases we cannot book it later than 15 minutes after the search.

The change should affect just the booking payment status, not the flow

2020-11-23 08:59 UTC, closed without merging