added endpoint for getting invitations sent by me and all invitations…
happy-travel/edo pull request #297
Opened 2020-11-19 10:57 UTC by DFSko

… to my agency

2020-11-19 18:20 UTC, mingazhev requested changes

2020-11-19 18:20 UTC, mingazhev commented on Api/Controllers/AgentControllers/AgentsController.cs
> +        ///    Get agency invitations list
Summary should answer a question "what does method do", like "Gets agency invitations list"

2020-11-19 18:20 UTC, mingazhev commented on Api/Controllers/AgentControllers/AgentsController.cs
> +        [ProducesResponseType(typeof(List<AgentInvitationInfo>), (int) HttpStatusCode.OK)]
Please add a permission attribute there, I think something like "AgentManagement" will be appropriate

2020-11-19 18:20 UTC, mingazhev commented on Api/Controllers/AgentControllers/AgentsController.cs
> +        [InAgencyPermissions(InAgencyPermissions.ReceiveAgencyInvitations)]
I think this attribute on the wrong place. And if you meant "viewing", lets make it "Observe". Receiving invitations looks like invitations are received by mail or something similar

2020-11-19 18:20 UTC, mingazhev commented on Api/Services/Users/IUserInvitationService.cs
> +        Task<List<AgentInvitationInfo>> GetInvitationsByAgent(int agentId);
This service is common for admins and agents. Why does it contain agent-specific methods?

2020-11-20 03:31 UTC, DFSko commented on Api/Controllers/AgentControllers/AgentsController.cs
> +        ///    Get agency invitations list
Fixed

2020-11-20 03:31 UTC, DFSko commented on Api/Controllers/AgentControllers/AgentsController.cs
> +        [ProducesResponseType(typeof(List<AgentInvitationInfo>), (int) HttpStatusCode.OK)]
Fixed

2020-11-20 03:31 UTC, DFSko commented on Api/Controllers/AgentControllers/AgentsController.cs
> +        [InAgencyPermissions(InAgencyPermissions.ReceiveAgencyInvitations)]
Fixed

2020-11-20 03:41 UTC, DFSko commented on Api/Services/Users/IUserInvitationService.cs
> +        Task<List<AgentInvitationInfo>> GetInvitationsByAgent(int agentId);
Fixed

2020-11-20 06:22 UTC, mingazhev requested changes

2020-11-20 06:22 UTC, mingazhev commented on Api/Controllers/AgentControllers/AgentsController.cs
> +            var agentInvitationInfo = new AgentInvitationInfo(request.RegistrationInfo, request.AgencyId, agent.AgentId, request.Email);
As soon we get all the context for agent in agentContext (including an agency too), agencyId should not be passed from frontend side

2020-11-20 06:22 UTC, mingazhev commented on Api/Controllers/AgentControllers/AgentsController.cs
> +            var agentInvitationInfo = new AgentInvitationInfo(request.RegistrationInfo, request.AgencyId, agent.AgentId, request.Email);
This looks like a domain object inside constructor.
Why not passing the request to service and constructing this object inside the service?

2020-11-20 06:22 UTC, mingazhev commented on Api/Models/Agents/SendAgentInvitationRequest.cs
> +        /// <summary>
This should not be there

2020-11-20 06:22 UTC, mingazhev commented on HappyTravel.Edo.Common/Enums/InAgencyPermissions.cs
>              AgencyBookingsManagement |
You should add a migration to update rights for agents which have "All" permissions. For reference look at "20201110131233_AddIsActiveToRelation"

2020-11-20 07:46 UTC, DFSko commented on Api/Controllers/AgentControllers/AgentsController.cs
> +            var agentInvitationInfo = new AgentInvitationInfo(request.RegistrationInfo, request.AgencyId, agent.AgentId, request.Email);
Fixed

2020-11-20 07:46 UTC, DFSko commented on Api/Controllers/AgentControllers/AgentsController.cs
> +            var agentInvitationInfo = new AgentInvitationInfo(request.RegistrationInfo, request.AgencyId, agent.AgentId, request.Email);
Fixed

2020-11-20 07:46 UTC, DFSko commented on Api/Models/Agents/SendAgentInvitationRequest.cs
> +        /// <summary>
Fixed

2020-11-20 07:46 UTC, DFSko commented on HappyTravel.Edo.Common/Enums/InAgencyPermissions.cs
>              AgencyBookingsManagement |
Fixed

2020-11-20 18:08 UTC, mingazhev approved these changes

2020-11-21 10:46 UTC, merged