changed credit card payment flow
happy-travel/edo pull request #307
Opened 2020-11-23 08:59 UTC by DFSko

2020-11-23 14:29 UTC, mingazhev requested changes

2020-11-24 10:03 UTC, mingazhev requested changes

2020-11-24 10:03 UTC, mingazhev commented on Api/Services/Accommodations/Bookings/CreditCardPaymentConfirmationService.cs
> +                .Tap(SendReceipt)
We've decided to use tap only for situation when result is not modified.
If you want to use the Result, use Bind

2020-11-24 10:53 UTC, DFSko commented on HappyTravel.Edo.Data/Booking/CreditCardPaymentConfirmation.cs
> +        public int AgentId { get; set; }
Administrator has agency Id?

2020-11-24 11:14 UTC, DFSko commented on HappyTravel.Edo.Data/Booking/CreditCardPaymentConfirmation.cs
> +        public int AgentId { get; set; }
Maybe rename AgentId to AdministratorId?

2020-11-24 11:28 UTC, DFSko commented on Api/Services/Accommodations/Bookings/CreditCardPaymentConfirmationService.cs
> +            async Task<Result<Booking, ProblemDetails>> SaveConfirmation(Booking booking)
Fixed

2020-11-24 11:28 UTC, DFSko commented on Api/Services/Accommodations/Bookings/CreditCardPaymentConfirmationService.cs
> +                .Tap(SendReceipt)
Fixed

2020-11-25 01:52 UTC, mingazhev commented on HappyTravel.Edo.Data/Booking/CreditCardPaymentConfirmation.cs
> +        public int AgentId { get; set; }
Sure, AdministratorId

2020-11-25 07:03 UTC, closed without merging