fixed results count calculated without search settings
happy-travel/edo pull request #325
Opened 2020-11-27 09:38 UTC by DFSko

2020-11-27 10:52 UTC, mingazhev commented on Api/Services/Accommodations/Availability/Steps/WideAvailabilitySearch/WideAvailabilitySearchTask.cs
> +                var searchSettings = await _accommodationBookingSettingsService.Get(agent);
Why not getting this once and passing settings as method param?

2020-11-27 11:10 UTC, DFSko commented on Api/Services/Accommodations/Availability/Steps/WideAvailabilitySearch/WideAvailabilitySearchTask.cs
> +                var searchSettings = await _accommodationBookingSettingsService.Get(agent);
Fixed

2020-11-27 14:51 UTC, mingazhev requested changes

2020-11-27 14:51 UTC, mingazhev commented on Api/Services/Accommodations/Availability/Steps/WideAvailabilitySearch/WideAvailabilitySearchTask.cs
> +            _accommodationBookingSettingsService = accommodationBookingSettingsService;
Is it still used?

2020-11-27 14:51 UTC, mingazhev reviewed
Looks like unused field left

2020-11-27 21:35 UTC, DFSko commented on Api/Services/Accommodations/Availability/Steps/WideAvailabilitySearch/WideAvailabilitySearchTask.cs
> +            _accommodationBookingSettingsService = accommodationBookingSettingsService;
Removed

2020-11-28 10:05 UTC, mingazhev approved these changes

2020-11-28 11:41 UTC, merged