Feature/nijo 1088 agent markup bonuses
happy-travel/edo pull request #353
Opened 2020-12-09 05:50 UTC by DFSko

2020-12-09 06:40 UTC, mingazhev requested changes

2020-12-09 06:40 UTC, mingazhev commented on HappyTravel.Edo.Data/Payments/MarkupPaymentLog.cs
> +        public DateTime CreatedAt { get; set; }
Just `Created` as it is named in other tables

2020-12-09 06:40 UTC, mingazhev commented on Api/Services/Accommodations/Bookings/BookingRecordsManager.cs
> +                    .Select(a => new BookingMarkup
I think it will be more suitable to name such entity with `Applied` word to make it clear that this is AppliedMarkup

2020-12-09 06:40 UTC, mingazhev commented on Api/Services/Accommodations/Bookings/BookingMarkupService.cs
> +            _context.BookingMarkups.AddRange(appliedMarkups);
This service is too thin. I think it will be better to pass something less specific as parameters from outside and map to saving entities inside a method

2020-12-09 06:40 UTC, mingazhev commented on Api/Services/Accommodations/Bookings/BookingMarkupService.cs
> +    public class BookingMarkupService : IBookingMarkupService
BoookingMarkupService sounds too common, as a "main service for booking markups".
But it's meaning is not so wide, it just saves applied markups (not an entry point for all booking markup operations)

2020-12-09 06:40 UTC, mingazhev commented on Api/Services/Accommodations/Bookings/BookingRecordsManager.cs
> +                    .Select(a => new BookingMarkup
And another thing, this service should not be responsible for adding proper entities to the database, it should delegate such things to the calling service

2020-12-09 06:40 UTC, mingazhev commented on Api/Services/Markups/IMarkupPaymentService.cs
> +        Task<Result> Pay(string referenceCode);
Is this a "payment"? Not something like materalizing bonus?
Let's remove this from this step and PR, and do in separate

2020-12-09 06:40 UTC, mingazhev commented on Api/Services/Markups/MarkupPaymentService.cs
> +            if(bookingMarkupPayment.Equals(default))
Looks like formatting issue

2020-12-09 06:40 UTC, mingazhev commented on Api/Services/Markups/MarkupPaymentService.cs
> +                    join bookingMarkup in _context.BookingMarkups on markupPolicy.Id equals bookingMarkup.PolicyId
Would it work when there will be more than one applied markup? Our logic allows such

2020-12-09 06:40 UTC, mingazhev commented on Api/Services/Payments/MarkupPaymentAuditLogService.cs
> +        public async Task Write(MarkupPaymentLog paymentLog)
Too thin service again. You should not pass entity to service just to save it in db.
Either inline this code or move some additional logic inside a service

2020-12-10 03:57 UTC, DFSko commented on HappyTravel.Edo.Data/Payments/MarkupPaymentLog.cs
> +        public DateTime CreatedAt { get; set; }
Removed from this PR

2020-12-10 03:57 UTC, DFSko commented on Api/Services/Accommodations/Bookings/BookingRecordsManager.cs
> +                    .Select(a => new BookingMarkup
Fixed

2020-12-10 03:58 UTC, DFSko commented on Api/Services/Accommodations/Bookings/BookingMarkupService.cs
> +            _context.BookingMarkups.AddRange(appliedMarkups);
Fixed

2020-12-10 03:58 UTC, DFSko commented on Api/Services/Accommodations/Bookings/BookingMarkupService.cs
> +    public class BookingMarkupService : IBookingMarkupService
Fixed

2020-12-10 03:58 UTC, DFSko commented on Api/Services/Markups/IMarkupPaymentService.cs
> +        Task<Result> Pay(string referenceCode);
Removed from this PR

2020-12-10 03:58 UTC, DFSko commented on Api/Services/Markups/MarkupPaymentService.cs
> +            if(bookingMarkupPayment.Equals(default))
Removed from this PR

2020-12-10 03:58 UTC, DFSko commented on Api/Services/Markups/MarkupPaymentService.cs
> +                    join bookingMarkup in _context.BookingMarkups on markupPolicy.Id equals bookingMarkup.PolicyId
Removed from this PR

2020-12-10 03:58 UTC, DFSko commented on Api/Services/Payments/MarkupPaymentAuditLogService.cs
> +        public async Task Write(MarkupPaymentLog paymentLog)
Removed from this PR

2020-12-10 07:46 UTC, mingazhev approved these changes
With comments

2020-12-10 07:46 UTC, mingazhev commented on Api/Services/Accommodations/Bookings/AppliedBookingMarkupRecordsManager.cs
> +        public async Task Create(Booking booking, IEnumerable<AppliedMarkup> appliedMarkups)
Sending just a reference code will be enough

2020-12-10 07:46 UTC, mingazhev commented on HappyTravel.Edo.Data/Booking/AppliedBookingMarkup.cs
> +        public DateTime? Payed { get; set; }
Paid

2020-12-10 09:12 UTC, DFSko commented on Api/Services/Accommodations/Bookings/AppliedBookingMarkupRecordsManager.cs
> +        public async Task Create(Booking booking, IEnumerable<AppliedMarkup> appliedMarkups)
Fixed

2020-12-10 09:12 UTC, DFSko commented on HappyTravel.Edo.Data/Booking/AppliedBookingMarkup.cs
> +        public DateTime? Payed { get; set; }
Fixed

2020-12-10 09:38 UTC, kirillta approved these changes

2020-12-10 09:57 UTC, merged