added endpoint to move agent from one agency to another
happy-travel/edo pull request #405
Opened 2020-12-29 03:53 UTC by DFSko

2020-12-29 09:11 UTC, mingazhev requested changes
Could not see counterparty change logic 
![изображение](https://user-images.githubusercontent.com/43397444/103272869-c36a7280-49df-11eb-87a8-3da0d63ea579.png)

2020-12-29 13:30 UTC, mingazhev commented
> 
> 
> Could not see counterparty change logic
> ![изображение](https://user-images.githubusercontent.com/43397444/103272869-c36a7280-49df-11eb-87a8-3da0d63ea579.png)

This is an error comment, sorry

2020-12-29 13:38 UTC, mingazhev commented on Api/Models/Management/AuditEvents/AgentMovedFromOneAgencyToAnother.cs
> +        public int DestinationAgencyId { get; }
`Target` looks more suitable as anthonym for `source`

2020-12-29 13:38 UTC, mingazhev commented on Api/Services/Management/IChangeAgentAgencyService.cs
> +    public interface IChangeAgentAgencyService
IAgentMovementService maybe?

2020-12-29 13:38 UTC, mingazhev commented on Api/Services/Management/ChangeAgentAgencyService.cs
> +            return await IsAgentExist()
Method is named like returning bool, but returns Result instead

2020-12-29 13:38 UTC, mingazhev commented on HappyTravel.Edo.Common/Enums/ManagementEventType.cs
> +        MoveAgentFromOneAgencyToAnother = 70
This should be a noun. `AgentMovement` maybe?

2020-12-30 02:25 UTC, DFSko commented on Api/Models/Management/AuditEvents/AgentMovedFromOneAgencyToAnother.cs
> +        public int DestinationAgencyId { get; }
Fixed

2020-12-30 02:26 UTC, DFSko commented on Api/Services/Management/IChangeAgentAgencyService.cs
> +    public interface IChangeAgentAgencyService
Fixed

2020-12-30 02:26 UTC, DFSko commented on Api/Services/Management/ChangeAgentAgencyService.cs
> +            return await IsAgentExist()
Fixed

2020-12-30 02:26 UTC, DFSko commented on HappyTravel.Edo.Common/Enums/ManagementEventType.cs
> +        MoveAgentFromOneAgencyToAnother = 70
Fixed

2020-12-30 07:23 UTC, mingazhev commented on Api/Controllers/AdministratorControllers/ManagementController.cs
> +        public async Task<IActionResult> MoveAgentToAgency([FromBody] ChangeAgentAgencyRequest request)
I think you should:
1. Move this to AgentsController
2. Change the route according to rest rules, with agent and agency in the path (as it is done in `SetSystemSettings` endpoint)
3. Return ProblemDetails for bad request

2020-12-30 07:23 UTC, mingazhev commented on Api/Models/Management/ChangeAgentAgencyRequest.cs
> +        public int DestinationAgencyId { get; }
...

2020-12-30 07:23 UTC, mingazhev commented on Api/Services/Management/AgentMovementService.cs
> +            return await Result.Success()
Looks like you can remove this line

2020-12-30 09:23 UTC, DFSko commented on Api/Controllers/AdministratorControllers/ManagementController.cs
> +        public async Task<IActionResult> MoveAgentToAgency([FromBody] ChangeAgentAgencyRequest request)
Fixed

2020-12-30 09:23 UTC, DFSko commented on Api/Models/Management/ChangeAgentAgencyRequest.cs
> +        public int DestinationAgencyId { get; }
Fixed

2020-12-30 09:23 UTC, DFSko commented on Api/Services/Management/AgentMovementService.cs
> +            return await Result.Success()
Fixed

2020-12-30 12:05 UTC, mingazhev approved these changes

2020-12-30 12:13 UTC, merged