implemented service for booking status refreshing
happy-travel/edo pull request #433
Opened 2021-01-18 13:03 UTC by DFSko

2021-01-18 16:23 UTC, kirillta requested changes

2021-01-18 16:23 UTC, kirillta commented on Api/Services/Accommodations/Bookings/Management/BookingRefreshStatusService.cs
> +            BookingStatuses.Pending
Why here's only one status? All temporal and positively confirmed statuses must be checked time to time

2021-01-18 16:23 UTC, kirillta commented on Api/Services/Accommodations/Bookings/Management/BookingRefreshStatusService.cs
> +        private static readonly Dictionary<int, TimeSpan> Delays = new()
`DelayStrategies` I guess

2021-01-18 16:23 UTC, kirillta commented on Api/Services/Accommodations/Bookings/Management/BookingRefreshStatusService.cs
> +                    builder.AppendLine(error);
You may add negative results to `Result` directly

2021-01-18 16:23 UTC, kirillta commented on Api/Services/Accommodations/Bookings/Management/BookingRefreshStatusService.cs
> +                    return Result.Failure($"Cannot refresh booking status for booking {booking.ReferenceCode}. Reason: {booking.Status} status is wrong");
1. What means wrong?
2. Why not simply skip unsuitable statuses?

2021-01-18 16:23 UTC, kirillta commented on Api/Services/Accommodations/Bookings/Management/BookingRefreshStatusService.cs
> +        public async Task<Result> RefreshStatus(Booking booking, UserInfo userInfo, List<BookingRefreshStatusState> states = null)
Check of a single booking is a special case of a booking list check, so I advise to rewrite the service on top of `RefreshStatuses` method. That would be more efficient and save a lot of cycles

2021-01-18 16:23 UTC, kirillta commented on Api/Models/Bookings/BookingRefreshStatusState.cs
> +    public record BookingRefreshStatusState
`Status` and `State` mean the same, so it should be either `BookingRefreshState`, either `BookingStatusRefreshState`

2021-01-19 03:08 UTC, DFSko commented on Api/Services/Accommodations/Bookings/Management/BookingRefreshStatusService.cs
> +    public class BookingRefreshStatusService : IBookingRefreshStatusService
Fixed

2021-01-19 03:08 UTC, DFSko commented on Api/Controllers/AgentControllers/InternalBookingsController.cs
> +        [HttpPost("refresh-booking-status")]
Fixed

2021-01-19 03:08 UTC, DFSko commented on Api/Services/Accommodations/Bookings/Management/BookingRefreshStatusService.cs
> +        private static readonly Dictionary<int, TimeSpan> Delays = new()
Fixed

2021-01-19 03:09 UTC, DFSko commented on Api/Models/Bookings/BookingRefreshStatusState.cs
> +    public record BookingRefreshStatusState
Fixed

2021-01-19 03:31 UTC, DFSko commented on Api/Services/Accommodations/Bookings/Management/BookingRefreshStatusService.cs
> +                    return Result.Failure($"Cannot refresh booking status for booking {booking.ReferenceCode}. Reason: {booking.Status} status is wrong");
Fixed texts

2021-01-19 05:25 UTC, DFSko commented on Api/Services/Accommodations/Bookings/Management/BookingRefreshStatusService.cs
> +        public async Task<Result> RefreshStatus(Booking booking, UserInfo userInfo, List<BookingRefreshStatusState> states = null)
Fixed

2021-01-19 10:45 UTC, mingazhev commented on Api/Models/Bookings/BookingStatusRefreshState.cs
> +        public DateTime LastRefreshingDate { get; init; }
"LastRefreshDate" I think will sound better

2021-01-19 10:45 UTC, mingazhev commented on Api/Services/Accommodations/Bookings/Management/BookingStatusRefreshService.cs
> +        private static readonly HashSet<BookingUpdateModes> BookingUpdateModesForRefresh = new()
Should update not only synchronous bookings

2021-01-19 11:10 UTC, DFSko commented on Api/Services/Accommodations/Bookings/Management/IBookingRefreshStatusService.cs
> +        Task<List<int>> GetBookingsForUpdate();
Fixed

2021-01-19 11:10 UTC, DFSko commented on Api/Models/Bookings/BookingStatusRefreshState.cs
> +        public DateTime LastRefreshingDate { get; init; }
Fixed

2021-01-19 11:11 UTC, DFSko commented on Api/Services/Accommodations/Bookings/Management/BookingStatusRefreshService.cs
> +        private static readonly HashSet<BookingUpdateModes> BookingUpdateModesForRefresh = new()
Fixed

2021-01-19 11:15 UTC, DFSko commented on Api/Services/Accommodations/Bookings/Management/BookingRefreshStatusService.cs
> +        private static readonly HashSet<BookingUpdateModes> BookingUpdateModesForRefresh = new()
Fixed

2021-01-19 12:13 UTC, mingazhev approved these changes

2021-01-19 12:23 UTC, kirillta approved these changes

2021-01-19 12:40 UTC, merged