Feractor invitations and add child agency invitation
happy-travel/edo pull request #508
Opened 2021-03-02 19:13 UTC by Raibo

No migration yet

All controllers requests and responses formats kept the same.

2021-03-03 04:13 UTC, mingazhev requested changes

2021-03-03 04:13 UTC, mingazhev commented on Api/AdministratorServices/AgencyManagementService.cs
> +            var now = DateTime.UtcNow;
IDateTimeProvider

2021-03-03 04:13 UTC, mingazhev commented on Api/Extensions/InvitationInfoExtensions.cs
> +            => new UserInvitationData(new AgentEditableInfo(info.Title, info.FirstName, info.LastName, info.Position, info.Email), default);
AdministratorInvitationInfo cannot be bound to AgentEditableInfo, at least by name

2021-03-03 04:13 UTC, mingazhev commented on Api/Services/Invitations/InvitationService.cs
> +        private readonly AgentRegistrationNotificationOptions _notificationOptions;
Refactoring that has a result as more than 400 line class looks not like a good refactoring. Especially when classes were smaller before. Please look at style guide for reference 
https://github.com/happy-travel/docs/wiki/Style-Guides-%5C-Code-Styles

2021-03-03 04:13 UTC, mingazhev commented on Api/Services/Invitations/InvitationService.cs
> +                    UserInvitationTypes.Administrator => AdminInvitation(invitation),
These repeating switches all around the service look like a design problem: 
https://refactoring.guru/replace-conditional-with-polymorphism

2021-03-03 04:13 UTC, mingazhev commented on Api/Services/Invitations/InvitationService.cs
> +                    UserInvitationTypes.Administrator => AdminInvitation(invitation),
As a result: methods became too large with no need

2021-03-03 04:35 UTC, mingazhev requested changes

2021-03-03 04:35 UTC, mingazhev commented on Api/Services/Invitations/InvitationService.cs
> +                    .Bind(CreateAgent)
This responsibility looks like not belonging to "Invitation". I you'd like to make a generic invitation service, single for all, there must be no other domain parts - like adding agents, admins, relations etc.
Otherwise this service will bind all the separate domain parts together.

2021-03-03 11:21 UTC, Raibo commented on Api/Extensions/InvitationInfoExtensions.cs
> +            => new UserInvitationData(new AgentEditableInfo(info.Title, info.FirstName, info.LastName, info.Position, info.Email), default);
This is made to keep old API in tact.
We can change the API, but this will require work on the front end side, so let's do it later.

2021-03-03 13:42 UTC, kirillta commented on Api/AdministratorServices/IAgencyManagementService.cs
> +        Task<AgencyInfo> Create(string name, int counterpartyId, int? parentId);
I suggest `parentAgencyId`

2021-03-03 13:42 UTC, kirillta commented on HappyTravel.Edo.Common/Enums/UserInvitationStatuses.cs
> +        Disabled = 2,
`Sent` and `Revoked` maybe?

2021-03-03 13:42 UTC, kirillta commented on HappyTravel.Edo.Common/Enums/UserInvitationStatuses.cs
> +        Resent = 3,
Why do we need this state?

2021-03-03 13:42 UTC, kirillta commented on Api/Controllers/AgentControllers/AgenciesController.cs
> +        ///     Invites to create child agency.
Invites who or where?

2021-03-03 13:42 UTC, kirillta commented on Api/Services/Invitations/InvitationService.cs
> +                    true,
Add a name explicitly here

2021-03-03 13:42 UTC, kirillta commented on Api/Services/Invitations/InvitationService.cs
> +                bool IsEmailFilled() => !string.IsNullOrWhiteSpace(invitationData.AgentRegistrationInfo.Email);
What do you mean _filled_? That's not clear

2021-03-03 13:50 UTC, Raibo commented on Api/Services/Invitations/InvitationService.cs
> +                    .Bind(CreateAgent)
Moved "Accept" into separate services for admins and agents

2021-03-03 13:55 UTC, Raibo commented on HappyTravel.Edo.Common/Enums/UserInvitationStatuses.cs
> +        Disabled = 2,
`Sent` could be misleading. For example, when invite was just generated and not sent.
`Disabled` is taken from old code (`Disable` method), but here's no reason not to change this one.

2021-03-03 13:58 UTC, Raibo commented on HappyTravel.Edo.Common/Enums/UserInvitationStatuses.cs
> +        Resent = 3,
Well, it was stored previously, in a separate bool column.
There is logic bound to this information too.
Also, this could be useful to know, that an invitation was not just disabled (or revoked), but rather resent, so there must be another one, possibly accepted.

2021-03-03 13:59 UTC, Raibo commented on Api/Controllers/AgentControllers/AgenciesController.cs
> +        ///     Invites to create child agency.
To do something (create an agency)

2021-03-03 14:00 UTC, Raibo commented on Api/Services/Invitations/InvitationService.cs
> +                    true,
Ok

2021-03-03 14:01 UTC, Raibo commented on Api/Services/Invitations/InvitationService.cs
> +                bool IsEmailFilled() => !string.IsNullOrWhiteSpace(invitationData.AgentRegistrationInfo.Email);
Filled means not empty.
Like, when you fill fields like name, etc.

2021-03-03 14:01 UTC, Raibo commented on Api/Services/Invitations/InvitationService.cs
> +                    UserInvitationTypes.Administrator => AdminInvitation(invitation),
I split services

2021-03-03 14:02 UTC, Raibo commented on Api/Services/Invitations/InvitationService.cs
> +        private readonly AgentRegistrationNotificationOptions _notificationOptions;
I split services

2021-03-03 14:02 UTC, Raibo commented on Api/AdministratorServices/AgencyManagementService.cs
> +            var now = DateTime.UtcNow;
Ok

2021-03-03 14:05 UTC, Raibo commented on Api/Extensions/InvitationInfoExtensions.cs
> +            => new UserInvitationData(new AgentEditableInfo(info.Title, info.FirstName, info.LastName, info.Position, info.Email), default);
Also have exactly same 5 fields.

2021-03-03 14:06 UTC, Raibo commented on Api/AdministratorServices/IAgencyManagementService.cs
> +        Task<AgencyInfo> Create(string name, int counterpartyId, int? parentId);
Ok

2021-03-03 14:06 UTC, Raibo commented on HappyTravel.Edo.Common/Enums/UserInvitationStatuses.cs
> +        Disabled = 2,
Renamed `Disabled` to `Revoked`

2021-03-03 20:44 UTC, kirillta commented on Api/Controllers/AgentControllers/AgenciesController.cs
> +        ///     Invites to create child agency.
Then "Invites an agent to create a child agency", I guess

2021-03-03 20:44 UTC, kirillta commented on Api/Infrastructure/ServiceCollectionExtensions.cs
> +                options.InvitationExpirationPeriod = TimeSpan.FromDays(7);
Move it to a constant, please

2021-03-04 09:18 UTC, Raibo commented on Api/Infrastructure/ServiceCollectionExtensions.cs
> +                options.InvitationExpirationPeriod = TimeSpan.FromDays(7);
Ok

2021-03-04 11:48 UTC, mingazhev requested changes
The main problem I see is oversized InvitationRecordManagement interface. Writed more in comments

2021-03-04 11:48 UTC, mingazhev commented on Api/Extensions/InvitationInfoExtensions.cs
> +            => new UserInvitationData(new AgentEditableInfo(info.Title, info.FirstName, info.LastName, info.Position, info.Email), default);
Don't see how this will affect existing API. If there will be a struct with another name or struct with the same list of fields.

2021-03-04 11:48 UTC, mingazhev commented on Api/Infrastructure/Options/InvitationRecordOptions.cs
> +        public string AgentInvitationTemplateId { get; set; }
Everywhere if possible we try to separate admin and agent services, I think it is a bad idea to concatenate them, especially for options.

2021-03-04 11:48 UTC, mingazhev commented on Api/Models/Invitations/UserInvitationData.cs
> +        public UserInvitationData(AgentEditableInfo agentRegistrationInfo,
Is this UserInvitationData or agent invitation data?
If it is common, why do it contain special agent and agency fields?
If not, why is it names in such way?

2021-03-04 11:48 UTC, mingazhev commented on Api/Services/Invitations/IInvitationRecordService.cs
> +    public interface IInvitationRecordService
Is it agent invitation record service (common for all) or agent invitation record service?
If it is common, why does it contain members, special for an agent?
If not, why is it named in such common way?
In any answer, interface has too much members (typically should not be more than 5-6).
And please look at interface segregation principle and single responsibility principles:

https://docs.microsoft.com/en-us/archive/msdn-magazine/2014/may/csharp-best-practices-dangers-of-violating-solid-principles-in-csharp

2021-03-04 11:48 UTC, mingazhev commented on Api/Services/Invitations/InvitationAcceptAdminService.cs
> +
Empty line

2021-03-04 11:48 UTC, mingazhev commented on Api/Services/Invitations/InvitationAcceptAgentService.cs
> +            Task<Result<UserInvitation>> GetActiveInvitation() => _invitationRecordService.GetActiveInvitation(invitationCode);
Arrow to the next line. Please use https://github.com/happy-travel/docs/wiki/Style-Guides-%5C-Code-Styles
for reference

2021-03-04 11:48 UTC, mingazhev commented on Api/Services/Invitations/InvitationAcceptAgentService.cs
> +            return await Result.Success()
This pipe is too long and hard to understand. Consider merging some methods to meaningful logical blocks, e.g. getting invitation, validation etc.

2021-03-04 14:30 UTC, Raibo commented on Api/Infrastructure/Options/InvitationRecordOptions.cs
> +        public string AgentInvitationTemplateId { get; set; }
This is not admin or user service, it's responsibility is invites.
The only mentions of admins and agents here are in template ids. There is no point doing two identical services doing same things just for the reason not to see words "admin" and "user" next to each other.

Everything related to actual user or admin entities is moved to separate services, one for admins and one for agents, as you suggested earlier.

2021-03-04 14:39 UTC, Raibo commented on Api/Models/Invitations/UserInvitationData.cs
> +        public UserInvitationData(AgentEditableInfo agentRegistrationInfo,
It is common.
As for agency fields, from my point of view, it is way easier to understand code, when for all invitations, one input struct is used, even if some of the fields are unused in some cases.

As for the naming, I would rather rename `AgentEditableInfo` into `UserInfo`, because currently `AgentEditableInfo` is not editable, and can describe not only agents, but also admins.
What do you think?

2021-03-04 14:46 UTC, Raibo commented on Api/Services/Invitations/IInvitationRecordService.cs
> +    public interface IInvitationRecordService
Single responsibility principle itself is ambiguous and can be looked at from different points of view in each case.
Here I can say that this service has a single responsibility of invitations.

If the interface has too much members, I can move the selection methods for agents/agencies to somewhere else.

2021-03-04 15:05 UTC, Raibo commented on Api/Services/Invitations/InvitationAcceptAgentService.cs
> +            Task<Result<UserInvitation>> GetActiveInvitation() => _invitationRecordService.GetActiveInvitation(invitationCode);
Ok

2021-03-04 15:05 UTC, Raibo commented on Api/Services/Invitations/IInvitationRecordService.cs
> +    public interface IInvitationRecordService
Moved the selection methods

2021-03-04 15:37 UTC, Raibo commented on Api/Services/Invitations/InvitationAcceptAgentService.cs
> +            return await Result.Success()
Merged validation and getting invitation, now pipe is easier to read.

2021-03-04 15:37 UTC, Raibo commented on Api/Models/Invitations/UserInvitationData.cs
> +        public UserInvitationData(AgentEditableInfo agentRegistrationInfo,
Renamed `AgentEditableInfo` to `UserDescriptionInfo`

2021-03-05 08:29 UTC, Raibo commented on Api/Extensions/InvitationInfoExtensions.cs
> +            => new UserInvitationData(new AgentEditableInfo(info.Title, info.FirstName, info.LastName, info.Position, info.Email), default);
Changed input parameter type to UserDescriptionInfo

2021-03-05 08:31 UTC, Raibo commented on Api/Extensions/InvitationInfoExtensions.cs
> +            => new UserInvitationData(new AgentEditableInfo(info.Title, info.FirstName, info.LastName, info.Position, info.Email), default);
Removed this method

2021-03-05 12:08 UTC, mingazhev commented on Api/Services/Invitations/InvitationRecordService.cs
> +            bool shouldSendInvitationMail, int inviterUserId, int? inviterAgencyId = null)
Since this service is common and can be used by different domain parts, why does it serve all of them in different manners?
If it is common, it should know nothing about the caller and its logic.
There is a part of common logic there, but calling agencyManagementService looks not like common.

2021-03-05 12:08 UTC, mingazhev commented on Api/Services/Invitations/InvitationRecordService.cs
> +                    AgencyName = agencyName,
Filling agency name for admin invitation looks like a bad idea, even if you set it to null

2021-03-05 12:08 UTC, mingazhev commented on Api/Services/Invitations/InvitationRecordService.cs
> +                    oldInvitation.InviterAgencyId);
Same there. Interface is pretty common, but the logic "knows" about agency id

2021-03-05 12:08 UTC, mingazhev commented on Api/Infrastructure/Options/InvitationRecordOptions.cs
> +        public string AgentInvitationTemplateId { get; set; }
I understood why they are in one struct, this is because they are used together, in a one service. This is incorrect too.

2021-03-05 15:24 UTC, Raibo commented on Api/Services/Invitations/IInvitationAcceptAdminService.cs
> +    public interface IInvitationAcceptAdminService
moved

2021-03-05 15:25 UTC, Raibo commented on Api/Services/Invitations/IInvitationRecordsListService.cs
> +    public interface IInvitationRecordsListService
Renamed

2021-03-05 15:28 UTC, Raibo commented on Api/Services/Invitations/InvitationRecordService.cs
> +                .Tap(SaveDisabled);
Revoked.
Renamed pipe method to `SaveRevoked`, but public method `Accept` -> `SetAccepted`, to reflect that it only changes state and does not actually accept the invite (create agent or admin etc.)

2021-03-05 15:28 UTC, Raibo commented on Api/Services/Invitations/IInvitationRecordService.cs
> +namespace HappyTravel.Edo.Api.Services.Invitations
moved

2021-03-09 06:44 UTC, mingazhev approved these changes

2021-03-09 14:06 UTC, mingazhev approved these changes

2021-03-09 14:06 UTC, mingazhev commented on Api/Infrastructure/Invitations/InvitationRecordService.cs
> +        public async Task<Result> SetResent(string code)
Fixed

2021-03-09 14:06 UTC, mingazhev commented on Api/Services/Invitations/AgentInvitationAcceptService.cs
> +                    .Ensure(IsInvitationCorrectType, "Incorrect invitation type")
Fixed

2021-03-09 14:06 UTC, merged