Added AgencyAccountsController for admin. Aded endpoints for get agen…
happy-travel/edo pull request #641
Opened 2021-04-19 20:46 UTC by AlexeyShok

Added AgencyAccountsController for admin. Aded endpoints for get agency accounts and put is active status for agency account.

2021-04-19 22:08 UTC, kirillta commented on Api/Controllers/AdministratorControllers/AgencyAccountsController.cs
> +        /// Sets agency account is active status
I suggest `Changes an agency account activity state` or something

2021-04-19 22:08 UTC, kirillta commented on Api/Models/Agencies/AgencyAccountFullInfo.cs
> +    public readonly struct AgencyAccountFullInfo
`FullAgencyAccountInfo`. Lets keep more natural language

2021-04-19 22:08 UTC, kirillta commented on Api/Models/Agencies/AgencyAccountSettings.cs
> +        public AgencyAccountSettings(bool isActive)
I suggest to add an agency ID as well

2021-04-19 22:08 UTC, kirillta commented on Api/Models/Agencies/AgencyAccountSettings.cs
> +        public AgencyAccountSettings(bool isActive)
Or an agency ID and an account ID

2021-04-20 05:34 UTC, AlexeyShok commented on Api/Controllers/AdministratorControllers/AgencyAccountsController.cs
> +        /// Sets agency account is active status
Fixed

2021-04-20 05:36 UTC, AlexeyShok commented on Api/Models/Agencies/AgencyAccountFullInfo.cs
> +    public readonly struct AgencyAccountFullInfo
Fixed

2021-04-20 05:53 UTC, AlexeyShok commented on Api/Models/Agencies/AgencyAccountSettings.cs
> +        public AgencyAccountSettings(bool isActive)
This model is only used to pass data in a request. Id agencies and accounts transferred in the route. Therefore, you do not need to add them to the model.

2021-04-20 08:45 UTC, kirillta requested changes

2021-04-20 08:45 UTC, kirillta commented on Api/Models/Agencies/AgencyAccountSettings.cs
> +        public AgencyAccountSettings(bool isActive)
I see the opposite: 
```csharp
await _accountPaymentService.SetAgencyAccountSettings(agencyId, agencyAccountId, agencyAccountSettings)
```

2021-04-20 10:11 UTC, kirillta approved these changes

2021-04-20 12:35 UTC, merged