Feature/aa 149 return accommodation photo url in rich booking model
happy-travel/edo pull request #645
Opened 2021-04-21 18:43 UTC by AlexeyShok

Added AccommodationInfo with Photo to AccommodationDetails model

2021-04-22 10:40 UTC, kirillta reviewed
`AccommodationInfo` should contain all related info in it

2021-04-24 17:21 UTC, mingazhev requested changes

2021-04-24 17:21 UTC, mingazhev commented on Api/Models/Accommodations/AccommodationInfo.cs
> +        public AccommodationInfo(ImageInfo photo)
Please do not use contracts (instead of enums) in frontend models. This causes lots of problems every time

2021-04-24 17:21 UTC, mingazhev commented on Api/Models/Accommodations/AccommodationInfo.cs
> +        public AccommodationInfo(ImageInfo photo)
By my experience it is fine to make a copy of a model to use inside EDO. At list typically it should be a class to work fine with EF

2021-04-26 05:58 UTC, AlexeyShok commented on Api/Models/Accommodations/AccommodationInfo.cs
> +        public AccommodationInfo(ImageInfo photo)
This model is not transferred to the front.

2021-04-26 15:00 UTC, mingazhev approved these changes

2021-04-26 15:04 UTC, merged