Added endpoint for changing counterparty account activity state
happy-travel/edo pull request #649
Opened 2021-04-23 18:03 UTC by AlexeyShok

Added endpoint for changing counterparty account activity state. Some refactoring

2021-04-24 12:18 UTC, kirillta approved these changes

2021-04-24 12:18 UTC, kirillta commented on Api/Controllers/AdministratorControllers/CounterpartyAccountsController.cs
> +        [ProducesResponseType(typeof(ProblemDetails), (int)HttpStatusCode.BadRequest)]
How can I get 400 from this method?

2021-04-24 12:21 UTC, kirillta reviewed
Sorry, Previously I misclick a button

2021-04-24 17:02 UTC, mingazhev requested changes

2021-04-24 17:02 UTC, mingazhev commented on Api/Controllers/AdministratorControllers/CounterpartyAccountsController.cs
> +            [FromBody] CounterpartyAccountRequest counterpartyAccountRequest)
What does this name mean? Request looks like requesting some action. Maybe CounterpartyAccountEditRequest?

2021-04-24 17:02 UTC, mingazhev commented on Api/Controllers/AdministratorControllers/CounterpartyAccountsController.cs
> +                return BadRequest(ProblemDetailsBuilder.Build(error));
Maybe using OkOrBadRequest from BaseController will be better

2021-04-26 04:55 UTC, AlexeyShok commented on Api/Controllers/AdministratorControllers/CounterpartyAccountsController.cs
> +        /// Changes a counterparty account activity state
Fixed

2021-04-26 04:59 UTC, AlexeyShok commented on Api/Controllers/AdministratorControllers/CounterpartyAccountsController.cs
> +            [FromBody] CounterpartyAccountRequest counterpartyAccountRequest)
Fixed

2021-04-26 05:01 UTC, AlexeyShok commented on Api/AdministratorServices/CounterpartyAccountService.cs
> +                .SingleOrDefaultAsync(aa => aa.CounterpartyId == counterpartyAccountSettings.CounterpartyId && aa.Id == counterpartyAccountSettings.CounterpartyAccountId);
Fixed

2021-04-26 05:02 UTC, AlexeyShok commented on Api/AdministratorServices/CounterpartyAccountService.cs
> +                Result.Failure($"Account Id {counterpartyAccountSettings.CounterpartyAccountId} not found in agency Id {counterpartyAccountSettings.CounterpartyId}");
Fixed

2021-04-26 05:02 UTC, AlexeyShok commented on Api/AdministratorServices/CounterpartyAccountService.cs
> +                .SingleOrDefaultAsync(aa => aa.CounterpartyId == counterpartyAccountSettings.CounterpartyId && aa.Id == counterpartyAccountSettings.CounterpartyAccountId);
Fixed

2021-04-26 05:03 UTC, AlexeyShok commented on Api/AdministratorServices/CounterpartyAccountService.cs
> +                Result.Failure($"Account Id {counterpartyAccountSettings.CounterpartyAccountId} not found in agency Id {counterpartyAccountSettings.CounterpartyId}");
Fixed

2021-04-26 05:10 UTC, AlexeyShok commented on Api/Controllers/AdministratorControllers/CounterpartyAccountsController.cs
> +                return BadRequest(ProblemDetailsBuilder.Build(error));
Fixed

2021-04-26 05:20 UTC, AlexeyShok commented on Api/Controllers/AdministratorControllers/CounterpartyAccountsController.cs
> +        [ProducesResponseType(typeof(ProblemDetails), (int)HttpStatusCode.BadRequest)]
Fixed

2021-04-26 06:28 UTC, mingazhev reviewed
Needs additional backend team discussion

2021-04-26 06:28 UTC, mingazhev commented on Api/Controllers/AdministratorControllers/AgencyAccountsController.cs
> +        [ProducesResponseType(typeof(ProblemDetails), (int) HttpStatusCode.NotFound)]
This line should be removed at all. Problem details cannot be returned with not found

2021-04-26 06:28 UTC, mingazhev commented on Api/Controllers/AdministratorControllers/AgencyAccountsController.cs
> +        [ProducesResponseType(typeof(ProblemDetails), (int) HttpStatusCode.NotFound)]
And the only available status code is 200 there

2021-04-26 19:46 UTC, mingazhev commented on Api/Controllers/AdministratorControllers/CounterpartyAccountsController.cs
> +        [HttpPut("counterparties/{counterpartyId}/accounts/{counterpartyAccountId}/deactivate")]
You should use "POST" + method name for all methods that change something and not have direct analogs in httpverbs.
Here verb is "deactivate"

2021-04-26 19:46 UTC, mingazhev commented on Api/Controllers/AdministratorControllers/CounterpartyAccountsController.cs
> +        [HttpPut("counterparties/{counterpartyId}/accounts/{counterpartyAccountId}/activate")]
Should be POST here too

2021-04-26 19:46 UTC, mingazhev commented on Api/Controllers/AdministratorControllers/AgencyAccountsController.cs
> +        [HttpGet("agencies/{agencyId}/accounts")]
Please check this with frontend side to not break something (maybe needs route changes on their side)

2021-04-26 19:46 UTC, mingazhev commented on Api/AdministratorServices/ICounterpartyAccountService.cs
> +        Task<Result> ActivateCounterpartyAccount(int counterpartyId, int counterpartyAccountId, string reason);
Just Activate and Deactivate names will be enough.
"Counterparty" and "Account" are already in interface name

2021-04-26 19:46 UTC, mingazhev commented on Api/AdministratorServices/IAgencyAccountService.cs
> +        Task<List<FullAgencyAccountInfo>> GetAgencyAccounts(int agencyId);
Just Get, Activate, Deactivate

2021-04-26 20:03 UTC, kirillta commented on Api/AdministratorServices/AgencyAccountService.cs
> +        public async Task<Result> DeactivateAgencyAccount(int agencyId, int agencyAccountId, string reason)
`ActivateAgencyAccount` and `DeactivateAgencyAccount` bases could be merged into one method

2021-04-26 20:26 UTC, AlexeyShok commented on Api/AdministratorServices/IAgencyAccountService.cs
> +        Task<List<FullAgencyAccountInfo>> GetAgencyAccounts(int agencyId);
Fixed

2021-04-26 20:26 UTC, AlexeyShok commented on Api/AdministratorServices/ICounterpartyAccountService.cs
> +        Task<Result> ActivateCounterpartyAccount(int counterpartyId, int counterpartyAccountId, string reason);
Fixed

2021-04-26 20:28 UTC, AlexeyShok commented on Api/Controllers/AdministratorControllers/CounterpartyAccountsController.cs
> +        [HttpPut("counterparties/{counterpartyId}/accounts/{counterpartyAccountId}/deactivate")]
Fixed

2021-04-26 20:29 UTC, AlexeyShok commented on Api/Controllers/AdministratorControllers/CounterpartyAccountsController.cs
> +        [HttpPut("counterparties/{counterpartyId}/accounts/{counterpartyAccountId}/activate")]
Fixed

2021-04-26 20:38 UTC, AlexeyShok commented on Api/AdministratorServices/AgencyAccountService.cs
> +        public async Task<Result> DeactivateAgencyAccount(int agencyId, int agencyAccountId, string reason)
Fixed

2021-04-26 20:47 UTC, AlexeyShok commented on Api/AdministratorServices/AgencyAccountService.cs
> +            => _context.AgencyAccounts
Fixed

2021-04-26 20:51 UTC, AlexeyShok commented on Api/Controllers/AdministratorControllers/AgencyAccountsController.cs
> +        [HttpGet("agencies/{agencyId}/accounts")]
Checked

2021-04-27 11:32 UTC, kirillta approved these changes

2021-04-27 13:02 UTC, mingazhev approved these changes

2021-04-27 13:05 UTC, hasmikharutyunyan commented on Api/AdministratorServices/AgencyAccountService.cs
> +            => await ChangeAccountActivity(agencyId, agencyAccountId, isActive: true);
why reason not used?

2021-04-27 13:11 UTC, AlexeyShok commented on Api/AdministratorServices/AgencyAccountService.cs
> +            => await ChangeAccountActivity(agencyId, agencyAccountId, isActive: true);
This will be implemented in task AA-167 https://github.com/happy-travel/agent-app-project/issues/167

2021-04-27 13:12 UTC, merged