Technical/aa 201 verify routes for restfulness v1
happy-travel/edo pull request #727
Opened 2021-06-09 11:57 UTC by hasmikharutyunyan

Done changes which affect only our services. 
@mingazhev, in matsumato and payment processing we will change also, after that we will merge this pull request.

2021-06-09 11:59 UTC, mingazhev approved these changes
It's ok and now need to sync clients:
Matsumoto and payment processing

2021-06-10 23:26 UTC, kirillta requested changes

2021-06-10 23:26 UTC, kirillta commented on Api/Controllers/AgentControllers/PaymentsController.cs
> +        [HttpPost("accommodations/bookings/pay-by-new-card")]
Probably `accommodations/bookings/cards/new/pay`?

2021-06-10 23:26 UTC, kirillta commented on Api/Controllers/AgentControllers/InternalBookingsController.cs
> +        [HttpGet("to-notify/deadline-approach")]
Why `to`?

2021-06-11 12:01 UTC, hasmikharutyunyan commented on Api/Controllers/AgentControllers/PaymentsController.cs
> +        [HttpPost("accommodations/bookings/pay-by-new-card")]
In previous PR was suggestion `pay-by-new-card`. And for me no difference because as I understand we have not separate entities new card and saved card.

2021-06-11 12:02 UTC, hasmikharutyunyan commented on Api/Controllers/AgentControllers/InternalBookingsController.cs
> +        [HttpGet("to-notify/deadline-approach")]
`for-notify` ? Or what you suggest?

2021-06-11 13:14 UTC, kirillta commented on Api/Controllers/AgentControllers/InternalBookingsController.cs
> +        [HttpGet("to-notify/deadline-approach")]
Leave as it is

2021-06-11 13:15 UTC, kirillta commented on Api/Controllers/AgentControllers/PaymentsController.cs
> +        [HttpPost("accommodations/bookings/pay-by-new-card")]
We have schemes where an entity goes before an action. `pay-by-new-card` violates the rule

2021-06-22 21:05 UTC, kirillta approved these changes

2021-07-05 10:57 UTC, merged